version: '3'

services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    environment:
      - VIRTUAL_HOST=whoami.backsoul.xyz
      - VIRUTAL_POST=80
      - LETSENCRYPT_HOST=whoami.backsoul.xyz
      - LETSENCRYPT_EMAIL=danielsarmientoenterprise@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
networks:
  web:
    external: true