version: '3'

services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    ports:
      - "80:8003"
    environment:
      - VIRTUAL_HOST=whoami.backsoul.xyz
      - VIRUTAL_POST=8003
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
networks:
  web:
    external: true

